### ISSUE TITLE
UX/UI Testing - #3816 [KOSMO] First set up moderation tab - part 2 - 

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-kosmo#100]
**URL:** https://kosmo-dev.liqd.net/userdashboard/overview/ and https://kosmo-dev.liqd.net/userdashboard/moderation/
**user:** *moderator*
**important screensize:** *Both*
**device & browser:** *Safari Version 14.0.3 (16610.4.3.1.7)*
**Comment/Question:** *I have added the comments in the pdf below, I didn't repeat the Desktop comments for Mobile cause it would look too much, so I just added what was a part from that on Mobile. 

Some stuff might be unclear, so let me know if you need any help*

[210413-d-moderation-tab.pdf](https://github.com/liqd/a4-kosmo/files/6305323/210413-d-moderation-tab.pdf)
[210413-m-moderation-tab.pdf](https://github.com/liqd/a4-kosmo/files/6305324/210413-m-moderation-tab.pdf)

**Comment by phillimorland** [comment]
@mcastro-lqd danke! some of these issues were fixed in the styling story that was merged yesterday and some are fixed in the issue fix pull request that is still outstanding, sorry there was some mis-communication with me and Katharina about when you should have been tagged for testing. But if you can double check the stuff below that would be awesome! :)

3. can you clear your cache? new logo should be there
7. are all projects you are following active? as the carousel only shows active projects 
8. tiles will be changes back in the issue fixing pull request

**Comment by phillimorland** [comment]
@mcastro-lqd oh and yes you can send me replacement icons

**Comment by phillimorland** [comment]
@mcastro-lqd 
mobile 03. what should I have for
