### ISSUE TITLE
normal user can access moderation dashboard

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-kosmo#136]
**URL:** see test https://github.com/liqd/a4-kosmo/blob/main/tests/projects/test_project_api.py
**user:** 
**expected behaviour:** I am not sure if we should forbid this.
**behaviour:** Currently the user can access the moderation dashboard, but the right rule is used in the view. 
**important screensize:**
**device & browser:** 
**Comment/Question:** 
https://github.com/liqd/a4-kosmo/commit/dfde4ad27682142838f1ac0eeac01c73910d3eec 
https://github.com/liqd/a4-kosmo/blob/main/apps/userdashboard/rules.py

**Comment by sabinammm** [comment]
Do you mean that we should decide to rather use object-level permissions like django guardian as described, e.g. here https://coderbook.com/@marcus/how-to-restrict-access-with-django-permissions/? What information do we need in order to make this decision?

**Comment by fuzzylogic2000** [comment]
@sabinammm No, we use the [django rules](https://github.com/dfunckt/django-rules), which work fine! It's just that they somehow are not used when accessing the moderation dashboard. I think. This issue is about investigating why. (and maybe it's not that important, because we do not show the tab to the normal user and if he gets the view, he can also not do anything there, because we also check the rules in the actions.

**Comment by Rineee** [comment]
@fuzzylogic2000 So this is not the access to the moderation dashboard, but to the moderation project api (which is used in moderation dashboard to get the projects).The permission for the api is IsAuthenticated (https://github.com/liqd/a4-kosmo/blob/570c345b5e84e95fd11061290b88a575251943bf/apps/projects/api.py#L39). I think this is fine, right? Because you can check for any authenticated user to get the moderation projects which returns an empty list if she is not a moderator? 

To view the moderation dashboard, the [UserDashboardModerationView](https://github.com/liqd/a4-kosmo/blob/570c345b5e84e95fd11061290b88a575251943bf/apps/userdashboard/views.py#L82) is used, which uses the right permission and is tested [here](https://github.com/liqd/a4-kosmo/blob/main/tests/userdashboard/test_rule_view_moderation.py).

I think the name of the test is misleading maybe? We could rename it to `test_moderator_can_get_moderation_projects` ?

**Comment by fuzzylogic2000** [comment]
@Rineee Cool, thank you! I will just change my comment and the naming then. :)
