### ISSUE TITLE
Sorting: AI sorting does not fit 

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#237]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/detail/debate-debate/
**user:** moderation
**expected behaviour:** I is clear what "most reported comments" refer to
**behaviour:** the sorting "most reported" does show the most reported "beleidigend" comments, but the AI is not taken into consideration - is that possible? The screenshot shows two notifications with the same amount of incivil reports and different numbers of the AI report, but the notification with the lower amount of AI reports is sorted higher.
**Comment/Question:** I am a little confused if this is from the latest change of the moderation dashboard. Before, there were many comments also from the AI. I am wondering if we do need the count of the AI? Is i included in the "most reported"?

![Bildschirmfoto 2022-05-19 um 11 15 45](https://user-images.githubusercontent.com/30862422/169261399-d683c1d3-90f1-4b8f-8b0c-47861fed45d7.png)

**Comment by Rineee** [comment]
@hmkay Good that you are asking, because it is indeed confusing. Currently the AI count counts the number of reports that come from the AI. So, in your example above, in the first comment, there must be 2 user reports that reported that comment as offensive, thus there are 5 offensive reports, but only 3 come from AI. The sorting is according to the total number of reports (ai+user). However, I also find that number on the AI tag confusing (especially because it kind of double counts the number of reports e.g. in the example above, one could think there are 8 reports altogether, even though there are only 5 of which 3 are from the AI). I hope that was understandable :) 

So: maybe we can just delete the AI count? Or, if we want to show it, we should maybe also show the number of user reports? And somehow show them differently than the other counts, so thy don't get confused with those?

Maybe @fuzzylogic2000 has also some thoughts on that :)

**Comment by fuzzylogic2000** [comment]
I don't have any more thoughts than what you already said. I guess @rilanari @hmkay and @mcastro-lqd need to decide how and if we want to show which classifications are from the user and which are from AI.

**Comment by Rineee** [comment]
> _e.g. in the example above, one could think there are 8 reports altogether, even though there are only 5 of which 3 are from the AI). I hope that was understandable :)_ - If that's the case, why do you say that the sorting is according to the total number of reports (ai+user)? Cause It doesn't seem to be the total amount of reports. Cause in this case the first one would be a total of 8 and the second a total of 9.
> 
@mcastro-lqd Well no.. the total number of reports is in both cases is 5, of which for the first comment 3 are from the AI (and 2 from user, which is not visible) and for the second comment 4 are from AI (and 1 from user). Since the sorting only takes number of reports in account, they are both on top of the list with 5 reports each.. 

> @Rineee Stupid question see_no_evil: how can the AI report more than 1 time something as offensive?

This happens when the comment is edited, then it is sent to the AI again..

> To be honest, that's why I was never a fan of the AI counter, from my point of view, AI shouldn't be displayed there cause it's a different classification, but if you want to keep it I would count (ai + user) and display them by the total amount, in this case first 9 then 8.

**Comment by Rineee** [comment]
Haha, sorry for the double explanation @mcastro-lqd, didnt see @fuzzylogic2000s comment..

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 @Rineee No worries! Thanks for clarifying. I just got confused cause I understood **ai + user** meaning the total amount, not **user - ai** (extracting the ai number):D

**Comment by hmkay** [comment]
Ha, thank you so much for the discussion - it really is confusing :D 
Yes, then I would also go with the suggestion to delete the count of the AI and only show the total amount of reports and in case of a classification by the AI, just to indicate it with an AI tag but the AI tag does not have a count.

**Comment by mcastro-lqd** [comment]
Maybe we can use a checkmark instead to show that it was "verified" by the ai  
![Screenshot 2022-05-24 at 10 43 36](https://user-images.githubusercontent.com/59610786/169989628-40697f8b-93ca-4124-b7ef-6464e48e7a05.png)

**Comment by hmkay** [comment]
Yes! If that is still easy to do?

**Comment by fuzzylogic2000** [comment]
@hmkay Yes sure, we can put a checkmark there instead, but that still does not make sense to me. In the first example, there would be
`offensive 5` `AI check`
when there are three offensive classifications by the AI and two user reports. But it looks like it was all AI.

**Comment by mcastro-lqd** [comment]
I mean, I just tried to come up with a quick solution, you can leave how you prefer, I don't mind. 

What I still don't get is why does it matter if it was done by ai or people?

**Comment by hmkay** [comment]
You are right, @fuzzylogic2000 , it is still confusing. I think this is due to the appearance of the reports and the AI tag. Maybe for now we can remove the AI count and then need to think if we change the AI tag not only with the check mark, but maybe also differantiate it by place and colour or form.

**Comment by hmkay** [comment]
@mcastro-lqd yes, good question. For me it is about the transparency that we would like to have on the platform indicating when the AI communicates with oneself. This would be the need behind the AI tag.

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 @hmkay That's why I mentioned Im fine with both, from my perspective, the point that `offensive 5` `AI check` is confusing is also applicable to `offensive 5` `AI`.

**Comment by hmkay** [comment]
Then the question would be: Do we see that we can enhance that still with low effort? Should we shortly meet?

**Comment by fuzzylogic2000** [comment]
Options:
1. leave it like it is `offensive 5` `AI 3`
-> is confusing because there is no explanation and the tags look the same

2. remove the number `offensive 5` `AI check`
-> is fullfilling the need of indicating that there were classifications of the AI. But unless there are only either AI or user reports, it does not really add info and is still confusing

3. remove the AI tag `offensive 5`
-> fits with the counts from the sorting. Does not show if the classifications are given by AI or user.

4. indicate AI and user on the labels themselves `user: offensive 2` `AI: offensive 3`
-> might be too much info

5. use a different label `offensive 5` ----- _user 2_ _AI 3_
-> will get confusing again if there are other classifications (`offensive 5` `engaging 1` ----- _user 2_ _AI 4_)

6. use a different classification for the reports (currently the AI can add three different classifications, while the user can only report a comment and thus adds an "offensive" classification `offensive 3` `user report 2`

There are probably more options, but these are the ones I could think of. I think, I would like 3 or 6.

**Comment by Rineee** [comment]
I really like 6!

**Comment by mcastro-lqd** [comment]
In the end I tried to help with solutions and I ended up creating more doubts, so as I didn't come up with the AI tag, I would say it's up to you, but if you want to know my opinion: Favorite is **3** then 2 or without the checkmark `offensive 5` `AI` 

_(Also, can the AI detect a high quality comment or fact claim? I thought it was only offensive comments.)_

**Comment by hmkay** [comment]
No worries, @mcastro-lqd , you didn´t create more doubts, you just made me aware of inconsistencies, so thank you for that! I really appreciate your view and opinion!

I still feel it would be good to talk about it once, also to think about maybe future implications. So I would suggest we meet.

**Comment by hmkay** [comment]
Ok. So I am coming back to asynch discussion :D

The problem we would like to solve is:
- indicate if there are many reports from people
- indicate when the AI communicated with the moderator in order to make it transparent
- have not too much info on the tiles as it also confuses.

What about the option 2 with a slightly different AI tag (eg form, colour, place)?

And yes, the AI now is learning to detect a high quality comment or fact claim. That is quite exciting :)

**Comment by Rineee** [comment]
@hmkay I now added the AI label with a checkmark and without the count, you can check it out on dev.. what do you think?

**Comment by hmkay** [comment]
Thank you, @Rineee ! This already looks clearer to me than before and it also indicates that the AI tag is something different than the category. I also understand that we have some room for enhancement, but this will be for later. I think for now, we can leave it like this. Thank you!
