### ISSUE TITLE
moderation: overview of projects: tiles indication unclear

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-kosmo#238]
**URL:** https://kosmo-dev.liqd.net/userdashboard/moderation/
**user:** moderation
**expected behaviour:** The tiles show number of pending reports and indicate new where something new happend and tell moderators which project is most important
**behaviour:** tiles show all the reports, also the number of archived notifications; also the blue dot does not go away

**Comment/Question:** 

Screenshot?
![Bildschirmfoto 2022-05-19 um 11 43 18](https://user-images.githubusercontent.com/30862422/169264405-de48086a-cb21-4889-a888-b72454423b45.png)

**Comment by Rineee** [comment]
@hmkay Yes, that also comes from our change, also already thought that we need to adapt that.
So, what number do we want to show in Meldungen? Probably the number of comments that have at least one pending notification? Or the total number of pending notifications?

And the blue dot should go away once there are no more pending notifications, right?

**Comment by hmkay** [comment]
Thank you, @Rineee and @fuzzylogic2000 ! So, for "Meldungen" it should be all pending notifications. 

For the blue dot, I think it was initially thought to be "unread" - meaning new notifications since the last time the moderator logged in (if I am not mistaken, @mcastro-lqd ). I dunno if we have this information, though. Otherwise I think the blue dot is good to indicate that there are pending notifications, even though it is double information, because it is also written on the tile.

So...hm. Maybe @mcastro-lqd can say something to the blue dot from his expertise?

**Comment by mcastro-lqd** [comment]
@hmkay @Rineee @fuzzylogic2000 The blue dot was created to have the same behaviour as unread emails, sms, social media notifications. If something new has happened, the blue dot would appear. 

From my perspective, **Meldungen** should be the amount of unarchived notifications left to be reviewed and **Kommentare** should be the total amount of reported comments Unarchived + Archived (except the Moderator Statements) 

but I'm open for discussion

**Comment by hmkay** [comment]
I think *Kommentare* was meant to indicate the amount of all the comments in one discussion. This would be also interesting for the moderation and it makes visible how much traffic there is in one discussion. 

So I guess the decisions/questions are:
- question to @Rineee and @fuzzylogic2000 : can we use the dot as "unread" from the technical side?
- Question to @mcastro-lqd : Are you fine if *Kommentare* indicate the amount of comments in one discussion? Or do we need another indicator, such as another word?
- Decision: *Meldungen* are unarchived notifications left to be reviewed

**Comment by mcastro-lqd** [comment]
@hmkay Sure, if it's relevant for the moderation, you can display them all.

**Comment by hmkay** [comment]
perfect! Thanks, @mcastro-lqd !

**Comment by Rineee** [comment]
> Thank you, @Rineee and @fuzzylogic2000 ! So, for "Meldungen" it should be all pending notifications. Thus the number would show the amount of all pending notifications

Sorry to ask again, but just to be sure we mean the same thing: by amount of pending notifications, you mean the amount of comments, that have at least one pending notification? Or, I will put it in an example: If we have a comment with offensive:2 and another comment with enaging:1, the count should show 
a) 2 or 
b) 3
? :see_no_evil: To me, a) makes more sense (because there are only 2 tiles)?
@hmkay @fuzzylogic2000

**Comment by Rineee** [comment]
> * question to @Rineee and @fuzzylogic2000 : can we use the dot as "unread" from the technical side?

We do have the last_login of the user and we could compare if there are pending notifications that were created since. But I am unsure if that makes sense, because we cant mark them as read (only archived). So, while the user stays logged in, this blue dot would not go away (unless he/she archives all of them), even if he/she saw the notifications.. do you know what I mean?

Also, I think implementing this would rather be a small story than an issue, because we never really worked on that (see original story [here](https://taiga.liqd.net/project/mkay-kosmo/us/7)). Currently the blue dot is there when there is at least one notification, no matter if archived or not. 

An easier solution would be to simply show the blue dot when there are comments with pending notifications. It would be inline with the number of Meldungen, so it would always be there if there are some Meldungen. What do you think @hmkay ?

**Comment by Rineee** [comment]
Cool, thanks!
