### ISSUE TITLE
Overview Dashboard: Project Sorting

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-kosmo#313]
**URL:** https://kosmo-dev.liqd.net/userdashboard/overview/
**user:** *all*
**important screensize:** *Both*
**device & browser:** *Version 15.6 (17613.3.9.1.5)*
**Comment/Question:** *Just to confirm, I thought we mentioned that the default sorting here was supposed to be the project that has more new comments first, right? If that's not possible or we changed them after Sprint Planing, forget about it.* 

<img width="1010" alt="Screenshot 2022-08-16 at 12 02 48" src="https://user-images.githubusercontent.com/59610786/184853664-dfb55267-4916-49aa-9456-4040edde3e12.png">

**Comment by phillimorland** [comment]
@mcastro-lqd the sorting was not in the user story and it was discussed that if we only ever show the last commented then they would always bee the ones shown and the projects ending sooner should be the ones shown, however looking at your tiles that also doesn't seem to be happening, @Rineee any idea why 'Debate debate' would be shown before 'Rines Testproject' shouldn't it be the other way around?

**Comment by Rineee** [comment]
@phillimorland Yes, I know why that is, it is because Rines Testprojekt has another module that ends after debate debate and thus is second in the list, but on the tile we show the remaining days or the currently active project that ends next. I explained it more in detail in this [issue](https://github.com/liqd/adhocracy-plus/issues/1076) and @fredewe and @lthueer made a story out of it. I think we should really tackle that soon as it is very confusing!

**Comment by Rineee** [comment]
So I will close the issue, hope thats fine!
